### ISSUE TITLE
Feature: special 'allhostnames' group containing all ansible_hosts

### ISSUE THREAD

**Issue by Manuelraa** [Manuelraa/yaml_folder_inventory#52]
Sometimes instead of instances we want to target all the actuall hosts. Would be good if this can be done e.g. this way:
```
- name: Do something with hosts
  hosts: allhostnames
  tasks:
    ...
```

The feature should be added as a possible config value which can be defined in `inventory` section of the `ansible.cfg`
